### ISSUE TITLE
blind call transfer improvement

### ISSUE THREAD

**Issue by ikq** [versatica/JsSIP#556]
I found problem with the blind call transfer scenario:

1. 1st phone send REFER to 2nd
2. 2nd: REFER accepted, and start calling to 3rd
3. According RFC 5589 1st phone should not here send BYE to 2nd until receive NOTIFY with final call result.
   But ... 1st phone send BYE to 2nd !
4. Now then 3rd phone accept incoming from 2nd phone call, in the 2nd will try send NOTIFY to 1st.
   But it will failed, then it will close 2nd-3rd phone call, and there will be exception.....
   Seems the difficult case did not implemented.

According description CISCO: "https://www.cisco.com/c/en/us/td/docs/ios/voice/sip/configuration/guide/12_4t/sip_12_4t_book/sip_cg-call_x-fer.pdf", page 8. Figure 2.
It's still possible send REFER and then immediately BYE
Better in the case then 2nd phone continue to call to 3rd, and then establish the call without problem.

Proposed fix in file: ReferNotifier.js
Don't send NOTIFY if dialog (that receive REFER) is terminated.

notify(code, reason)
  {
    debug('notify()');

    if (this._active === false)
    {
      return;
    }
	
	if( this._session.status === this._session.C.STATUS_TERMINATED) //     Proposed fix: 
	{                                                                                                      //      Don't try send NOTIFY
		this._active = false;                                                                 //      if dialog is terminated.
		return;                                                                                    //
	}                                                                                                      //

**Comment by ikq** [comment]
Yes, after 1st phone send BYE, it don’t receive NOTIFY.

Problem with 2nd phone, seems there some exception when notifier try to send NOTIFY.
I can provide logs from 2nd phone, if you want.

**Comment by jmillan** [comment]
Ok, then provide us the full JsSIP logs for the 2nd phone.

**Comment by ikq** [comment]
Hi !

Here the logs of my test phone and jssip

phone1 (user web1), and phone2 (user web2), call transferred to phone3 (user web3)

I send also build jssip.js, because I think added fix of ICE timeout can a little change lines numbers.

Scenario


  1.  Phone1  (user web1) call to phone2 user web2,
  2.  Phone2 answer, call is established.
  3.  Phone1 set call on hold.
  4.  Phone1 send to Phone2 REFER with request to call phone3 (user web3)
  5.  REFER is accepted, Phone2 starts calling to Phone3
  6.  (!) Phone1 hangup call (send BYE) to phone2
  7.  Phone3 answer to incoming call, call between phone2 and phone3 is establish.
  8.  Phone2 now trying send NOTIFY to phone1. But the call is terminated already.

IMHO, here there is problem, see phone2.txt, line 820.




Regards,
Igor




From: Igor Kolosov
Sent: Monday, December 24, 2018 15:37
To: versatica/JsSIP <reply@reply.github.com>
Subject: RE: [versatica/JsSIP] blind call transfer improvement (#556)

Yes, after 1st phone send BYE, it don’t receive NOTIFY.

Problem with 2nd phone, seems there some exception when notifier try to send NOTIFY.
I can provide logs from 2nd phone, if you want.

**Comment by ikq** [comment]
Hi José Luis Millán,

outlook blocked sending file with .js extension.
So I’ll send it again with txt extension.

From: Igor Kolosov
Sent: Monday, December 24, 2018 16:06
To: 'versatica/JsSIP' <reply@reply.github.com>
Subject: RE: [versatica/JsSIP] blind call transfer improvement (#556)


Hi !

Here the logs of my test phone and jssip

phone1 (user web1), and phone2 (user web2), call transferred to phone3 (user web3)

I send also build jssip.js, because I think added fix of ICE timeout can a little change lines numbers.

Scenario


  1.  Phone1  (user web1) call to phone2 user web2,
  2.  Phone2 answer, call is established.
  3.  Phone1 set call on hold.
  4.  Phone1 send to Phone2 REFER with request to call phone3 (user web3)
  5.  REFER is accepted, Phone2 starts calling to Phone3
  6.  (!) Phone1 hangup call (send BYE) to phone2
  7.  Phone3 answer to incoming call, call between phone2 and phone3 is establish.
  8.  Phone2 now trying send NOTIFY to phone1. But the call is terminated already.

IMHO, here there is problem, see phone2.txt, line 820.




Regards,
Igor




From: Igor Kolosov
Sent: Monday, December 24, 2018 15:37
To: versatica/JsSIP <reply@reply.github.com>
Subject: RE: [versatica/JsSIP] blind call transfer improvement (#556)

Yes, after 1st phone send BYE, it don’t receive NOTIFY.

Problem with 2nd phone, seems there some exception when notifier try to send NOTIFY.
I can provide logs from 2nd phone, if you want.

**Comment by jmillan** [comment]
Only logs are needed, not any .js file.

The issue is that JsSIP is trying to send a NOTIFY upon failure event. By that moment the `RTCSession` is already closed.

Anyway is not clear to me why the session is failing. Please log the error message on the `RTCSession::failed` event callback and attach the `logs` for the 2nd phone.

**Comment by jmillan** [comment]
Please @ikq, 

Build and try JsSIP master branch. It should be fixed.

**Comment by ikq** [comment]
OK, thanks.

Currently I tried set breakpoint in phone2:

Seems problem here:

function sendRequest(method, options){
   debug(‘sendRequest()’);
  return this._dialog.sendRequest(method, options)
}

Here this is OK.
But _dialog === undefined.

**Comment by jmillan** [comment]
Let us know if master branch is working as expected.

**Comment by ikq** [comment]
Hi !

Still have the problem, with 3.3.2 version, please see attached log.

Regards,
Igor

**Comment by jmillan** [comment]
The change was made to master branch[1] and there is no new release yet.

Have you built[2] JsSIP out of master and tried?

[1]: https://github.com/versatica/JsSIP/commit/e3fdf420f92f1cddb75d30f528f509b78e3e3a80
[2]: https://github.com/versatica/JsSIP/blob/master/BUILDING.md

**Comment by ikq** [comment]
Opps, seem my problem.

I get the build: git clone https://github.com/versatica/JsSIP.git JsSIP

What’s I should do ?

**Comment by jmillan** [comment]
Follow the [building](https://github.com/versatica/JsSIP/blob/master/BUILDING.md) instructions and use the resulting .js in /dist folder on your app.

**Comment by ikq** [comment]
If you need to test, i'm happy to help
ikq.

**Comment by ikq** [comment]
Other proposed fix, according yours comment :  "// Put this in a try/catch block."

File ReferNotifier.js: Method: notify()


`  notify(code, reason)
  {
    debug('notify()');

    if (this._active === false)
    {
      return;
    }
	
    reason = reason || JsSIP_C.REASON_PHRASE[code] || '';

    let state;

    if (code >= 200)
    {
      state = 'terminated;reason=noresource';
    }
    else
    {
      state = `active;expires=${this._expires}`;
    }

    // Put this in a try/catch block.
	try {
      this._session.sendRequest(JsSIP_C.NOTIFY, {
        extraHeaders : [
          `Event: ${C.event_type};id=${this._id}`,
          `Subscription-State: ${state}`,
          `Content-Type: ${C.body_type}`
        ],
        body          : `SIP/2.0 ${code} ${reason}`,
        eventHandlers : {
        // If a negative response is received, subscription is canceled.
          onErrorResponse() { this._active = false; }
        }
      });
	} catch(e){
		debug('sendRequest exception - ignored', e);
	}
  }
`

You can see in the phone2 log that the fix described problem. 
During sending NOTIFY was exception, but it was catched and ignored.


13:42:58.537 phone.js:148 ------ Date: Tue Dec 25 2018 -------
13:42:58.541 phone.js:148 Browser: Chrome/71.0.3578.98
13:42:58.541 phone.js:148 SIP: JsSIP 3.2.15
13:42:58.542 phone.js:148 AudioCodes API: 1.5.0
13:42:58.543 phone.js:148 Used default phoneServerConfig
13:42:58.544 phone.js:148 Used default phoneConfig
13:42:58.548 phone.js:148 AudioPlayer: downloadSounds ["ring"]
13:42:58.559 phone.js:148 hasCamera=true
13:42:58.560 phone.js:148 Used custom phoneAccount
13:42:58.562 phone.js:148 Page reloading, raise priority of previously connected server: "wss://webrtclab.audiocodes.com"
13:42:58.563 phone.js:148 AC: setServerConfig() {addresses: Array(1), domain: "audiocodes.com", iceServers: Array(2)}
13:42:58.565 phone.js:148 AC: setReconnectIntervals min=2 max=30
13:42:58.565 phone.js:148 AC: setRegisterExpires=600
13:42:58.566 phone.js:148 AC: setUseSessionTimer=false
13:42:58.566 phone.js:148 AC: setChromeAudioConstraints= echoCancellation,googEchoCancellation,googExperimentalEchoCancellation,googDAEchoCancellation,googAutoGainControl,googNoiseSuppression,googHighpassFilter,googTypingNoiseDetection,googAudioMirroring
13:42:58.566 phone.js:148 AC: setWebSocketKeepAlive ping=10 pong=10 stats=60
13:42:58.567 phone.js:148 AC: setDtmfOptions useWebRTC=true duration=null interToneGap=null
13:42:58.567 phone.js:148 AC: setEnableAddVideo=true
13:42:58.567 phone.js:148 AC: setUserAgent=AudioCodes WebRTC phone
13:42:58.568 phone.js:148 AC: setListeners()
13:42:58.569 phone.js:148 AC: init() autoLogin=true
13:42:58.571 jssip.js:26614 new() [url:"wss://webrtclab.audiocodes.com"]
13:42:58.577 jssip.js:26614 new() [configuration:]
13:42:58.585 jssip.js:26614 new()
13:42:58.586 jssip.js:26614 configuration parameters after validation:
13:42:58.586 jssip.js:26614 - authorization_user: "web2"
13:42:58.587 jssip.js:26614 - password: NOT SHOWN
13:42:58.587 jssip.js:26614 - realm: null
13:42:58.587 jssip.js:26614 - ha1: NOT SHOWN
13:42:58.587 jssip.js:26614 - display_name: "Web2"
13:42:58.588 jssip.js:26614 - uri: sip:web2@audiocodes.com
13:42:58.588 jssip.js:26614 - contact_uri: {"_parameters":{"transport":"ws"},"_headers":{},"_scheme":"sip","_user":"p89np7fl","_host":"bim1lmj1bedh.invalid","_port":null}
13:42:58.589 jssip.js:26614 - instance_id: "27bed3f4-6193-4bfc-89da-828c8d8849bb"
13:42:58.589 jssip.js:26614 - use_preloaded_route: false
13:42:58.589 jssip.js:26614 - session_timers: false
13:42:58.589 jssip.js:26614 - session_timers_refresh_method: "UPDATE"
13:42:58.590 jssip.js:26614 - no_answer_timeout: 60000
13:42:58.590 jssip.js:26614 - register: true
13:42:58.590 jssip.js:26614 - register_expires: 600
13:42:58.590 jssip.js:26614 - registrar_server: sip:audiocodes.com
13:42:58.591 jssip.js:26614 - connection_recovery_max_interval: 30
13:42:58.591 jssip.js:26614 - connection_recovery_min_interval: 2
13:42:58.591 jssip.js:26614 - via_host: "bim1lmj1bedh.invalid"
13:42:58.593 jssip.js:26614 start()
13:42:58.593 jssip.js:26614 connect()
13:42:58.594 jssip.js:26614 connect()
13:42:58.594 jssip.js:26614 connecting to WebSocket wss://webrtclab.audiocodes.com
13:42:58.597 phone.js:148 call-log db: open
13:42:58.604 phone.js:148 call-log db: loaded 100
13:42:58.879 phone.js:148 audioPlayer: sounds are ready: {0: AudioBuffer, 1: AudioBuffer, 2: AudioBuffer, 3: AudioBuffer, 4: AudioBuffer, 5: AudioBuffer, 6: AudioBuffer, 7: AudioBuffer, 8: AudioBuffer, 9: AudioBuffer, ring: AudioBuffer, ringingTone: AudioBuffer, busyTone: AudioBuffer, *: AudioBuffer, #: AudioBuffer}
13:42:59.688 jssip.js:26614 WebSocket wss://webrtclab.audiocodes.com connected
13:42:59.688 phone.js:148 AC>>: loginStateChanged: isLogin=false "connected"
13:42:59.688 phone.js:148 phone>>> loginStateChanged: connected
13:42:59.688 jssip.js:26614 send()
13:42:59.698 jssip.js:26614 sending message:

REGISTER sip:audiocodes.com SIP/2.0
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK6519276
Max-Forwards: 69
To: <sip:web2@audiocodes.com>
From: "Web2" <sip:web2@audiocodes.com>;tag=rcmil5qpp1
Call-ID: aoskmasn0k1aqsfisq7p71
CSeq: 1 REGISTER
X-SBC: AudioCodes Mediant
Contact: <sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:27bed3f4-6193-4bfc-89da-828c8d8849bb>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: path,gruu,outbound
User-Agent: AudioCodes WebRTC phone
Content-Length: 0



13:42:59.698 jssip.js:26614 send()
13:42:59.921 jssip.js:26614 received WebSocket message
13:42:59.921 jssip.js:26614 received text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK6519276
From: "Web2" <sip:web2@audiocodes.com>;tag=rcmil5qpp1
To: <sip:web2@audiocodes.com>;tag=1c763382232
Call-ID: aoskmasn0k1aqsfisq7p71
CSeq: 1 REGISTER
www-authenticate: Digest realm="DefaultSipRealm",nonce="MjI1NTk5NTY1ODo3MzQzMzg5NQ==",qop="auth",algorithm=MD5
Content-Length: 0



13:42:59.960 jssip.js:26614 authenticate() | response generated
13:42:59.963 jssip.js:26614 send()
13:42:59.964 jssip.js:26614 sending message:

REGISTER sip:audiocodes.com SIP/2.0
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK279190
Max-Forwards: 69
To: <sip:web2@audiocodes.com>
From: "Web2" <sip:web2@audiocodes.com>;tag=rcmil5qpp1
Call-ID: aoskmasn0k1aqsfisq7p71
CSeq: 2 REGISTER
Authorization: Digest algorithm=MD5, username="web2", realm="DefaultSipRealm", nonce="MjI1NTk5NTY1ODo3MzQzMzg5NQ==", uri="sip:audiocodes.com", response="66ff1be7a2d0d26e39ba48991f7dd19b", qop=auth, cnonce="5ren8tid0tis", nc=00000001
X-SBC: AudioCodes Mediant
Contact: <sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance="<urn:uuid:27bed3f4-6193-4bfc-89da-828c8d8849bb>";expires=600
Expires: 600
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: path,gruu,outbound
User-Agent: AudioCodes WebRTC phone
Content-Length: 0



13:42:59.964 jssip.js:26614 send()
13:43:00.187 jssip.js:26614 received WebSocket message
13:43:00.187 jssip.js:26614 received text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK279190
From: "Web2" <sip:web2@audiocodes.com>;tag=rcmil5qpp1
To: <sip:web2@audiocodes.com>;tag=1c1504832979
Call-ID: aoskmasn0k1aqsfisq7p71
CSeq: 2 REGISTER
Contact: <sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws>;+sip.instance="<urn:uuid:27bed3f4-6193-4bfc-89da-828c8d8849bb>";expires=593;+sip.ice;reg-id=1
Allow: REGISTER,OPTIONS,INVITE,ACK,CANCEL,BYE,NOTIFY,PRACK,REFER,INFO,SUBSCRIBE,UPDATE
Expires: 593
Server: Mediant SW/v.7.20A.251.038
Content-Length: 0



13:43:00.197 phone.js:148 AC>>: loginStateChanged: isLogin=true "login"
13:43:00.197 phone.js:148 phone>>> loginStateChanged: login
13:43:08.106 jssip.js:26614 received WebSocket message
13:43:08.106 jssip.js:26614 received text message:

INVITE sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac285432223
Max-Forwards: 68
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
To: <sip:web2@audiocodes.com>
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 1 INVITE
Contact: <sip:FEU391-0-838-7@172.31.38.37:5060;transport=ws;ob>
Supported: ice,outbound,replaces,sdp-anat
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
User-Agent: Mediant SW/v.7.20A.251.038
Content-Type: application/sdp
Content-Length: 1085
X-Greeting: Nice to see you!

v=0
o=- 454827727 662142355 IN IP4 52.40.162.88
s=-
t=0 0
a=ice-lite
m=audio 6810 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 112 13 110 113 126
c=IN IP4 52.40.162.88
a=rtcp:6811 IN IP4 52.40.162.88
a=ice-ufrag:58DVQSLJcfa7y/Qo
a=ice-pwd:Nnqjow/nNb8VthQ2/QbMcw/8
a=fingerprint:sha-256 44:3E:CA:D6:9D:6A:C4:32:BD:D8:CA:8C:6A:23:04:75:7C:EE:4C:98:86:EB:54:83:87:18:92:EF:6D:E8:7D:76
a=setup:actpass
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1229330915 cname:0ZwYuzsmLKMTUZBl
a=candidate:632973449 1 udp 2130706431 52.40.162.88 6810 typ host
a=candidate:632973449 2 udp 2130706430 52.40.162.88 6811 typ host


13:43:08.116 jssip.js:26614 send()
13:43:08.116 jssip.js:26614 sending message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac285432223
To: <sip:web2@audiocodes.com>
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 1 INVITE
Supported: ice,replaces,outbound
Content-Length: 0



13:43:08.116 jssip.js:26614 send()
13:43:08.116 jssip.js:26614 new
13:43:08.116 jssip.js:26614 init_incoming()
13:43:08.116 jssip.js:26614 new UAS dialog created with status EARLY
13:43:08.116 jssip.js:26614 newRTCSession()
13:43:08.116 phone.js:148 AC: event incoming "newRTCSession" {originator: "remote", session: RTCSession, request: IncomingRequest}
13:43:08.116 phone.js:148 AC: peer connection does not exist, wait creation
13:43:08.116 phone.js:148 AC: [VIDEO] incoming call, temporary set video=false
13:43:08.126 phone.js:148 AC>>: incomingCall audio from "Web1" web1 AudioCodesSession {js_session: RTCSession, data: {…}}
13:43:08.126 phone.js:148 phone>>> incomingCall
13:43:08.126 phone.js:148 AudioPlayer: play: {name: "ring", loop: true, volume: 1, dropDisabled: true}
13:43:08.126 phone.js:148 desktopNotification created
13:43:08.126 jssip.js:26614 send()
13:43:08.126 jssip.js:26614 sending message:

SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac285432223
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 1 INVITE
Contact: <sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws>
Supported: ice,replaces,outbound
Content-Length: 0



13:43:08.136 jssip.js:26614 send()
13:43:08.136 jssip.js:26614 session progress
13:43:08.136 jssip.js:26614 emit "progress"
13:43:08.136 phone.js:148 call-log db: added
13:43:09.914 phone.js:148 AC: keep-alive: Server supports CRLF pong
13:43:11.987 phone.js:148 desktopNofification.close()
13:43:11.997 phone.js:148 AC: answer() audio
13:43:11.997 phone.js:148 AC: [VIDEO] according answer argument, set false
13:43:11.997 phone.js:148 AC: answer options: {mediaConstraints: {…}, pcConfig: {…}, extraHeaders: Array(1)}
13:43:11.997 jssip.js:26614 answer()
13:43:11.997 jssip.js:26614 dialog 135206406025122018114331@172.31.38.373jam0c2d0v1c1745614196  changed to CONFIRMED state
13:43:11.997 jssip.js:26614 emit "peerconnection"
13:43:12.007 phone.js:148 AC: [event connection] connection created, set "addstream" listener
13:43:12.047 jssip.js:26614 emit "sdp"
13:43:12.048 phone.js:148 AC: Event "sdp" ANSWERED (5) {originator: "remote", type: "offer", sdp: "v=0
↵o=- 454827727 662142355 IN IP4 52.40.162.88
↵…449 2 udp 2130706430 52.40.162.88 6811 typ host
↵"}
13:43:12.052 phone.js:148 [webrtc] >> connection addstream  MediaStream {id: "VoUtZekE2d5lqEoriEAVzO4mnnvpsJEVBTDj", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …} MediaStream {id: "default", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}
13:43:12.055 phone.js:148 AC>>: [connection addstream] callShowStreams AudioCodesSession {js_session: RTCSession, data: {…}} MediaStream {id: "VoUtZekE2d5lqEoriEAVzO4mnnvpsJEVBTDj", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …} MediaStream {id: "default", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}
13:43:12.057 phone.js:148 phone>>> callShowStreams
13:43:12.057 phone.js:148 video state: inactive
13:43:12.059 phone.js:148 hide local video view
13:43:12.060 phone.js:148 local audio:true  video:-
13:43:12.061 phone.js:148 remote audio:true  video:-
13:43:12.062 jssip.js:26614 session connecting
13:43:12.063 jssip.js:26614 emit "connecting"
13:43:12.063 jssip.js:26614 createLocalDescription()
13:43:12.296 jssip.js:26614 emit "sdp"
13:43:12.296 phone.js:148 AC: Event "sdp" ANSWERED (5) {originator: "local", type: "answer", sdp: "v=0
↵o=- 4389076745129562295 2 IN IP4 127.0.0.1
↵s…4341 label:e15e6d27-c06a-4caf-b34d-41b707465ee9
↵"}
13:43:12.298 jssip.js:26614 send()
13:43:12.299 jssip.js:26614 sending message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac285432223
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 1 INVITE
Contact: <sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws>
X-Greeting: You are welcome !
Supported: ice,replaces,outbound
Content-Type: application/sdp
Content-Length: 1475

v=0
o=- 4389076745129562295 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS VoUtZekE2d5lqEoriEAVzO4mnnvpsJEVBTDj
m=audio 60903 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 112 13 110 113 126
c=IN IP4 172.30.241.110
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:605072694 1 udp 2122260223 172.30.241.110 60903 typ host generation 0 network-id 1 network-cost 10
a=candidate:1788039622 1 tcp 1518280447 172.30.241.110 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:yqir
a=ice-pwd:MPUaZlbwM6y9OvaLhSU93VNH
a=ice-options:trickle
a=fingerprint:sha-256 67:9F:9C:6C:BE:36:09:8E:19:A6:2F:81:D1:40:DD:09:04:20:10:BF:19:15:0D:F1:27:93:44:DA:4E:80:CE:68
a=setup:active
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:112 telephone-event/32000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3339584341 cname:EQJatGFPeM53DVaI
a=ssrc:3339584341 msid:VoUtZekE2d5lqEoriEAVzO4mnnvpsJEVBTDj e15e6d27-c06a-4caf-b34d-41b707465ee9
a=ssrc:3339584341 mslabel:VoUtZekE2d5lqEoriEAVzO4mnnvpsJEVBTDj
a=ssrc:3339584341 label:e15e6d27-c06a-4caf-b34d-41b707465ee9


13:43:12.299 jssip.js:26614 send()
13:43:12.301 jssip.js:26614 session accepted
13:43:12.301 jssip.js:26614 emit "accepted"
13:43:12.750 jssip.js:26614 received WebSocket message
13:43:12.751 jssip.js:26614 received text message:

ACK sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac70990802
Max-Forwards: 68
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 1 ACK
Contact: <sip:FEU391-0-838-7@172.31.38.37:5060;transport=ws>
Supported: outbound
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
User-Agent: Mediant SW/v.7.20A.251.038
Content-Length: 0



13:43:12.755 jssip.js:26614 receiveRequest()
13:43:12.755 jssip.js:26614 session confirmed
13:43:12.756 jssip.js:26614 emit "confirmed"
13:43:12.756 phone.js:148 AC>>: callConfirmed AudioCodesSession {js_session: RTCSession, data: {…}, _remoteStreamAdded: true} ACK received
13:43:12.758 phone.js:148 phone>>> callConfirmed
13:43:12.765 phone.js:148 call-log db: updated
13:43:23.275 jssip.js:26614 received WebSocket message
13:43:23.275 jssip.js:26614 received text message:

INVITE sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac672941643
Max-Forwards: 68
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 2 INVITE
Contact: <sip:FEU391-0-838-7@172.31.38.37:5060;transport=ws;ob>
Supported: ice,outbound,replaces,sdp-anat
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
User-Agent: Mediant SW/v.7.20A.251.038
Content-Type: application/sdp
Content-Length: 1085

v=0
o=- 454827727 662142356 IN IP4 52.40.162.88
s=-
t=0 0
a=ice-lite
m=audio 6810 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 112 13 110 113 126
c=IN IP4 52.40.162.88
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=fmtp:111 minptime=10;useinbandfec=1
a=rtcp:6811 IN IP4 52.40.162.88
a=rtcp-fb:111 transport-cc
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=setup:actpass
a=sendonly
a=ice-ufrag:58DVQSLJcfa7y/Qo
a=ice-pwd:Nnqjow/nNb8VthQ2/QbMcw/8
a=fingerprint:sha-256 44:3E:CA:D6:9D:6A:C4:32:BD:D8:CA:8C:6A:23:04:75:7C:EE:4C:98:86:EB:54:83:87:18:92:EF:6D:E8:7D:76
a=ssrc:1229330915 cname:0ZwYuzsmLKMTUZBl
a=rtcp-mux
a=candidate:632973449 1 udp 2130706431 52.40.162.88 6810 typ host
a=candidate:632973449 2 udp 2130706430 52.40.162.88 6811 typ host


13:43:23.278 jssip.js:26614 send()
13:43:23.278 jssip.js:26614 sending message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac672941643
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 2 INVITE
Supported: ice,replaces,outbound
Content-Length: 0



13:43:23.279 jssip.js:26614 send()
13:43:23.280 jssip.js:26614 receiveRequest()
13:43:23.281 jssip.js:26614 receiveReinvite()
13:43:23.282 phone.js:148 AC>>: callIncomingReinvite start
13:43:23.283 phone.js:148 phone>>> call incoming reinvite start
13:43:23.284 jssip.js:26614 _processInDialogSdpOffer()
13:43:23.285 jssip.js:26614 emit "sdp"
13:43:23.286 phone.js:148 AC: Event "sdp" CONFIRMED (9) {originator: "remote", type: "offer", sdp: "v=0
↵o=- 454827727 662142356 IN IP4 52.40.162.88
↵…449 2 udp 2130706430 52.40.162.88 6811 typ host
↵"}
13:43:23.295 jssip.js:26614 session onhold
13:43:23.296 jssip.js:26614 emit "hold"
13:43:23.298 phone.js:148 AC>>: callHoldSholdStateChanged isHold=true isRemote=true session: AudioCodesSession {js_session: RTCSession, data: {…}, _remoteStreamAdded: true}
13:43:23.300 phone.js:148 phone>>> callHoldStateChanged
13:43:23.301 jssip.js:26614 createLocalDescription()
13:43:23.304 jssip.js:26614 emit "sdp"
13:43:23.305 phone.js:148 AC: Event "sdp" CONFIRMED (9) {originator: "local", type: "answer", sdp: "v=0
↵o=- 4389076745129562295 3 IN IP4 127.0.0.1
↵s…4341 label:e15e6d27-c06a-4caf-b34d-41b707465ee9
↵"}
13:43:23.307 jssip.js:26614 send()
13:43:23.307 jssip.js:26614 sending message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac672941643
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 2 INVITE
Contact: <sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws>
Supported: ice,replaces,outbound
Content-Type: application/sdp
Content-Length: 1475

v=0
o=- 4389076745129562295 3 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS VoUtZekE2d5lqEoriEAVzO4mnnvpsJEVBTDj
m=audio 60903 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 112 13 110 113 126
c=IN IP4 172.30.241.110
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:605072694 1 udp 2122260223 172.30.241.110 60903 typ host generation 0 network-id 1 network-cost 10
a=candidate:1788039622 1 tcp 1518280447 172.30.241.110 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:yqir
a=ice-pwd:MPUaZlbwM6y9OvaLhSU93VNH
a=ice-options:trickle
a=fingerprint:sha-256 67:9F:9C:6C:BE:36:09:8E:19:A6:2F:81:D1:40:DD:09:04:20:10:BF:19:15:0D:F1:27:93:44:DA:4E:80:CE:68
a=setup:active
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:112 telephone-event/32000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3339584341 cname:EQJatGFPeM53DVaI
a=ssrc:3339584341 msid:VoUtZekE2d5lqEoriEAVzO4mnnvpsJEVBTDj e15e6d27-c06a-4caf-b34d-41b707465ee9
a=ssrc:3339584341 mslabel:VoUtZekE2d5lqEoriEAVzO4mnnvpsJEVBTDj
a=ssrc:3339584341 label:e15e6d27-c06a-4caf-b34d-41b707465ee9


13:43:23.308 jssip.js:26614 send()
13:43:23.309 phone.js:148 AC>>: callIncomingIncomingReinvite end
13:43:23.310 phone.js:148 phone>>> call incoming reinvite end
13:43:23.787 jssip.js:26614 received WebSocket message
13:43:23.787 jssip.js:26614 received text message:

ACK sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac1555880847
Max-Forwards: 68
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 2 ACK
Contact: <sip:FEU391-0-838-7@172.31.38.37:5060;transport=ws>
Supported: outbound
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
User-Agent: Mediant SW/v.7.20A.251.038
Content-Length: 0



13:43:23.790 jssip.js:26614 receiveRequest()
13:43:24.201 jssip.js:26614 received WebSocket message
13:43:24.202 jssip.js:26614 received text message:

REFER sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac619958929
Max-Forwards: 68
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 3 REFER
Contact: <sip:FEU391-0-838-7@172.31.38.37:5060;transport=ws;ob>
Supported: outbound
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Refer-To: <sip:web3@audiocodes.com>
User-Agent: Mediant SW/v.7.20A.251.038
Content-Length: 0



13:43:24.205 jssip.js:26614 receiveRequest()
13:43:24.205 jssip.js:26614 receiveRefer()
13:43:24.206 jssip.js:26614 send()
13:43:24.207 jssip.js:26614 sending message:

SIP/2.0 202 Accepted
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac619958929
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 3 REFER
Supported: outbound
Content-Length: 0



13:43:24.207 jssip.js:26614 send()
13:43:24.209 jssip.js:26614 notify()
13:43:24.210 jssip.js:26614 sendRequest()
13:43:24.213 jssip.js:26614 send()
13:43:24.214 jssip.js:26614 sending message:

NOTIFY sip:FEU391-0-838-7@172.31.38.37:5060;transport=ws;ob SIP/2.0
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK6934555
Max-Forwards: 69
To: <sip:web1@audiocodes.com>;tag=1c1745614196
From: "Web2" <sip:web2@audiocodes.com>;tag=3jam0c2d0v
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 8203 NOTIFY
Event: refer;id=3
Subscription-State: active;expires=300
Content-Type: message/sipfrag;version=2.0
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: outbound
User-Agent: AudioCodes WebRTC phone
Content-Length: 18

SIP/2.0 100 Trying

13:43:24.215 jssip.js:26614 send()
13:43:24.215 jssip.js:26614 emit "refer"
13:43:24.216 phone.js:148 phone>>> transferee incoming REFER: accepted
13:43:24.217 phone.js:148 AC>>: incoming REFER accepted
13:43:24.218 jssip.js:26614 new
13:43:24.220 jssip.js:26614 connect()
13:43:24.224 jssip.js:26614 emit "peerconnection"
13:43:24.225 jssip.js:26614 newRTCSession()
13:43:24.225 phone.js:148 AC: event outgoing "newRTCSession" {originator: "local", session: RTCSession, request: InitialOutgoingInviteRequest}
13:43:24.226 phone.js:148 AC: connection exists, set "addstream" listener
13:43:24.227 phone.js:148 AC>>: outgoing call created by REFER
13:43:24.228 phone.js:148 phone>>> transferee created call AudioCodesSession {js_session: RTCSession, data: {…}}
13:43:24.235 jssip.js:26614 Timer J expired for transaction z9hG4bKac619958929
13:43:24.238 phone.js:148 call-log db: added
13:43:24.242 jssip.js:26614 session connecting
13:43:24.243 jssip.js:26614 emit "connecting"
13:43:24.244 jssip.js:26614 createLocalDescription()
13:43:24.898 jssip.js:26614 received WebSocket message
13:43:24.899 jssip.js:26614 received text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK6934555
From: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
To: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 8203 NOTIFY
Contact: <sip:FEU391-0-838-7@172.31.38.37:5060;transport=ws>
Supported: outbound
Server: Mediant SW/v.7.20A.251.038
Content-Length: 0



13:43:26.248 jssip.js:26614 [webrtc] ice gathering timeout
13:43:26.249 jssip.js:26614 emit "sdp"
13:43:26.249 phone.js:148 AC: Event "sdp" NULL (0) {originator: "local", type: "offer", sdp: "v=0
↵o=- 8654074390813285259 2 IN IP4 127.0.0.1
↵s…6901 label:1525e7e5-676d-4e16-905e-974e39c16f8e
↵"}
13:43:26.251 jssip.js:26614 emit "sending" [request:InitialOutgoingInviteRequest {ua: UA, headers: {…}, method: "INVITE", ruri: URI, body: "v=0
↵o=- 8654074390813285259 2 IN IP4 127.0.0.1
↵s…6901 label:1525e7e5-676d-4e16-905e-974e39c16f8e
↵", …}]
13:43:26.253 jssip.js:26614 send()
13:43:26.254 jssip.js:26614 sending message:

INVITE sip:web3@audiocodes.com SIP/2.0
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK2315572
Max-Forwards: 69
To: <sip:web3@audiocodes.com>
From: "Web2" <sip:web2@audiocodes.com>;tag=k6u3in9lpj
Call-ID: ut52uk55ktop2q8bu0e9
CSeq: 3623 INVITE
Contact: <sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws;ob>
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: ice,replaces,outbound
User-Agent: AudioCodes WebRTC phone
Content-Length: 1498

v=0
o=- 8654074390813285259 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS m8MSM2x1MDoss4S03EJJxHVN6gbjgnrvgAbY
m=audio 60908 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 172.30.241.110
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:605072694 1 udp 2122260223 172.30.241.110 60908 typ host generation 0 network-id 1 network-cost 10
a=candidate:1788039622 1 tcp 1518280447 172.30.241.110 9 typ host tcptype active generation 0 network-id 1 network-cost 10
a=ice-ufrag:jM7U
a=ice-pwd:AcZ/oeI13eISjiuGLcUPidwG
a=ice-options:trickle
a=fingerprint:sha-256 6D:74:9D:5F:DF:42:E1:6B:2C:43:F7:34:1C:14:31:54:BC:B4:81:6F:9D:9E:01:34:C1:43:65:ED:0E:0B:3B:74
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:3570746901 cname:jV9UhIDmqdparYCt
a=ssrc:3570746901 msid:m8MSM2x1MDoss4S03EJJxHVN6gbjgnrvgAbY 1525e7e5-676d-4e16-905e-974e39c16f8e
a=ssrc:3570746901 mslabel:m8MSM2x1MDoss4S03EJJxHVN6gbjgnrvgAbY
a=ssrc:3570746901 label:1525e7e5-676d-4e16-905e-974e39c16f8e


13:43:26.254 jssip.js:26614 send()
13:43:26.480 jssip.js:26614 received WebSocket message
13:43:26.480 jssip.js:26614 received text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK2315572
From: "Web2" <sip:web2@audiocodes.com>;tag=k6u3in9lpj
To: <sip:web3@audiocodes.com>
Call-ID: ut52uk55ktop2q8bu0e9
CSeq: 3623 INVITE
Server: Mediant SW/v.7.20A.251.038
Content-Length: 0



13:43:26.482 jssip.js:26614 receiveInviteResponse()
13:43:30.310 jssip.js:26614 received WebSocket message
13:43:30.311 jssip.js:26614 received text message:

BYE sip:p89np7fl@bim1lmj1bedh.invalid;transport=ws SIP/2.0
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac59353276
Max-Forwards: 68
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 4 BYE
Supported: outbound
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
User-Agent: Mediant SW/v.7.20A.251.038
Content-Length: 0



13:43:30.313 jssip.js:26614 receiveRequest()
13:43:30.313 jssip.js:26614 send()
13:43:30.313 jssip.js:26614 sending message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS 172.31.38.37:443;alias;branch=z9hG4bKac59353276
To: <sip:web2@audiocodes.com>;tag=3jam0c2d0v
From: "Web1" <sip:web1@audiocodes.com>;tag=1c1745614196
Call-ID: 135206406025122018114331@172.31.38.37
CSeq: 4 BYE
Supported: outbound
Content-Length: 0



13:43:30.314 jssip.js:26614 send()
13:43:30.315 jssip.js:26614 session ended
13:43:30.316 jssip.js:26614 close()
13:43:30.321 jssip.js:26614 close() | closing local MediaStream
13:43:30.322 jssip.js:26614 dialog 135206406025122018114331@172.31.38.373jam0c2d0v1c1745614196 deleted
13:43:30.322 jssip.js:26614 emit "ended"
13:43:30.323 phone.js:148 AC>>: callTerminated (ended) AudioCodesSession {js_session: RTCSession, data: {…}, _remoteStreamAdded: true} Terminated
13:43:30.325 phone.js:148 phone>>> call terminated callback, cause="Terminated"
13:43:30.325 phone.js:148 AC: duration(): returns 18
13:43:30.332 phone.js:148 Call log:  25 Dec 2018, 13:43:08 in web1 "Web1" 18 sec
13:43:30.334 phone.js:148 AudioPlayer: play: {name: "busyTone", volume: 0.2, repeat: 3}
13:43:30.339 jssip.js:26614 Timer J expired for transaction z9hG4bKac59353276
13:43:30.340 phone.js:148 call-log db: updated
13:43:33.213 phone.js:148 AudioPlayer: onended busyTone
13:43:41.536 jssip.js:26614 received WebSocket message
13:43:41.536 jssip.js:26614 received text message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK2315572
From: "Web2" <sip:web2@audiocodes.com>;tag=k6u3in9lpj
To: <sip:web3@audiocodes.com>;tag=ig49j1opmq
Call-ID: ut52uk55ktop2q8bu0e9
CSeq: 3623 INVITE
Contact: <sip:FEU391-0-848-7@172.31.38.37:443;transport=wss>
Supported: ice,outbound,replaces,sdp-anat
Server: Mediant SW/v.7.20A.251.038
Content-Type: application/sdp
Content-Length: 782
X-Greeting: You are welcome !

v=0
o=- 62916864 1284886114 IN IP4 52.40.162.88
s=-
t=0 0
a=ice-lite
m=audio 6815 UDP/TLS/RTP/SAVPF 111 103 9 0 8 105 13 110
c=IN IP4 52.40.162.88
a=ice-ufrag:m4GR4vCtFdmANIZL
a=ice-pwd:WArOhwx0z+tVVw/VeiPryzeL
a=fingerprint:sha-256 44:3E:CA:D6:9D:6A:C4:32:BD:D8:CA:8C:6A:23:04:75:7C:EE:4C:98:86:EB:54:83:87:18:92:EF:6D:E8:7D:76
a=setup:active
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=ssrc:4016164209 cname:Gepp+dBMFG4Y2K8a
a=candidate:1005414484 1 udp 2130706431 52.40.162.88 6815 typ host


13:43:41.536 jssip.js:26614 receiveInviteResponse()
13:43:41.536 jssip.js:26614 new UAC dialog created with status CONFIRMED
13:43:41.536 jssip.js:26614 emit "sdp"
13:43:41.536 phone.js:148 AC: Event "sdp" CONFIRMED (9) {originator: "remote", type: "answer", sdp: "v=0
↵o=- 62916864 1284886114 IN IP4 52.40.162.88
↵…484 1 udp 2130706431 52.40.162.88 6815 typ host
↵"}
13:43:41.546 phone.js:148 [webrtc] >> connection addstream  MediaStream {id: "m8MSM2x1MDoss4S03EJJxHVN6gbjgnrvgAbY", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …} MediaStream {id: "default", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}
13:43:41.546 phone.js:148 AC>>: [connection addstream] callShowStreams AudioCodesSession {js_session: RTCSession, data: {…}} MediaStream {id: "m8MSM2x1MDoss4S03EJJxHVN6gbjgnrvgAbY", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …} MediaStream {id: "default", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}
13:43:41.546 phone.js:148 phone>>> callShowStreams (transfer call)
13:43:41.546 jssip.js:26614 session accepted
13:43:41.546 jssip.js:26614 emit "accepted"
13:43:41.546 jssip.js:26614 notify()
13:43:41.546 jssip.js:26614 sendRequest()
13:43:41.556 jssip.js:26614 sendRequest exception - ignored TypeError: Cannot read property 'sendRequest' of undefined
    at RTCSession.sendRequest (jssip.js:18113)
    at ReferNotifier.notify (jssip.js:20567)
    at RTCSession.<anonymous> (jssip.js:18982)
    at emitOne (jssip.js:25818)
    at RTCSession.emit (jssip.js:25891)
    at RTCSession._accepted (jssip.js:20012)
    at jssip.js:19330
13:43:41.557 jssip.js:26614 sendRequest()
13:43:41.559 jssip.js:26614 send()
13:43:41.560 jssip.js:26614 sending message:

ACK sip:FEU391-0-848-7@172.31.38.37:443;transport=wss SIP/2.0
Via: SIP/2.0/WSS bim1lmj1bedh.invalid;branch=z9hG4bK1083124
Max-Forwards: 69
To: <sip:web3@audiocodes.com>;tag=ig49j1opmq
From: "Web2" <sip:web2@audiocodes.com>;tag=k6u3in9lpj
Call-ID: ut52uk55ktop2q8bu0e9
CSeq: 3623 ACK
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO
Supported: outbound
User-Agent: AudioCodes WebRTC phone
Content-Length: 0



13:43:41.561 jssip.js:26614 send()
13:43:41.562 jssip.js:26614 session confirmed
13:43:41.563 jssip.js:26614 emit "confirmed"
13:43:41.563 phone.js:148 AC>>: callConfirmed AudioCodesSession {js_session: RTCSession, data: {…}, _remoteStreamAdded: true} ACK sent
13:43:41.564 phone.js:148 phone>>> callConfirmed
13:43:41.568 phone.js:148 transfer call is established. Set it as active call
13:43:41.569 phone.js:148 hide local video view
13:43:41.577 phone.js:148 call-log db: updated
13:43:44.298 jssip.js:26614 Timer L expired for transaction z9hG4bKac285432223
13:43:55.307 jssip.js:26614 Timer L expired for transaction z9hG4bKac672941643
13:43:58.253 jssip.js:26614 Timer B expired for transaction z9hG4bK2315572
13:44:13.536 jssip.js:26614 Timer M expired for transaction z9hG4bK2315572

**Comment by ibc** [comment]
Could you please avoid so large comments? We don't need to see the entire and repeated log in every new response.

**Comment by ikq** [comment]
OK, I can edit them now to remove most of logs.

**Comment by heimiao** [comment]
每当我挂起电话时候，浏览器就崩溃。我注视掉图片里的代码即可
![AFD50E7A569F37EA4C51B02133AED524](https://user-images.githubusercontent.com/13977811/62444760-fe3b8d00-b790-11e9-93d9-41e01c105542.png)

就可以挂起来，但是接听不了电话。

**Comment by heimiao** [comment]
每当我挂起电话时，浏览器会崩溃。但我像图片似的注视掉代码就可以正常挂起，但是接听不了电话
![image](https://user-images.githubusercontent.com/13977811/62444912-730ec700-b791-11e9-825f-c8dfa0d493be.png)
![image](https://user-images.githubusercontent.com/13977811/62444920-7b670200-b791-11e9-9859-bffe5e69cb26.png)


我想实现同时打两路电话功能

**Comment by ibc** [comment]
Please @heimiao, stop polluting this issue with images unrelated to the topic of this issue. BTW the language of this issue tracker is English.

**Comment by heimiao** [comment]
When I make two calls at the same time, the browser crashes.

**Comment by ibc** [comment]
Sorry @heimiao, this is the last one. Use the JsSIP public mailing list (this is NOT the JsSIP mailing list) or you will be banned.

**Comment by heimiao** [comment]
When I make two calls at the same time, the browser crashes.

**Comment by jmillan** [comment]
@ikq,

Can you please send a full JsSIP log with the latest version showing this issue happening?

**Comment by ikq** [comment]
Yes the issue is happening in last version. 

Scenario: 
web1 call to web3
web3 accept call
web3 initiate blind transfer to web2
web3 hangup call.
web2 accept call
web1 try send NOTIFY to web3  and throws exception.
web1 send BYE to web2

Here full log with original jssip 3.3.6. You can see exception at end of log.

Note:
In log web1 BYE shown before exception, but really it initiated by the exception.

If use jssip where "this._session.sendRequest(JsSIP_C.NOTIFY, ... " enclosed to try / catch
and ignore catched exception,  web1 to web2 call will continue.






[blind_transfer.log](https://github.com/versatica/JsSIP/files/3491952/blind_transfer.log)

**Comment by ikq** [comment]
The issue is happening  also in latest 3.3.7 version

**Comment by heimiao** [comment]
I used last version JSSIP V3.3.6

Scenario:
Web1 call to web2
Web2 accept call
Web1 hold web2
Web1 call web3 
Now  the browser is died, I don’t have logs, because broswer was died . 
I hope you understand what I mean.
